### ISSUE TITLE
Renew automatico del token

### ISSUE THREAD

**Issue by juancentro** [matbarofex/rRofex#12]
Hoy cuando la conexion esta abierta mas de 24hs el token se vence y los requests fallan. Seria un buen feature que el package solo se de cuenta y lo renueve.

**Comment by augustohassel** [comment]
Hola! En el último push guarde las variables de logueo en .rRofexGlobalEnv. 
Ahora si te falla la conexión por tema del tokken te va a dar un error (y no como antes que crasheaba direcatmente). 
Creo que lo mejor sería armar la lógica de volver a loguear por fuera del paquete, para no meter tanto ruido en el paquete, y teniendo las credenciales esto debería ser bastante sencillo. 
Si hubiese una función de la API que valide el token se podría hacer mucho más fácil y sin impacto en la librería, pero no lo hay =/
Se te ocurre alguna manera simple de reloguear?
Saludos!

**Comment by augustohassel** [comment]
https://github.com/matbarofex/rRofex/releases/tag/v0.0.1.0000
