### ISSUE TITLE
Funcion para devolver tabla con estructura simil rueda

### ISSUE THREAD

**Issue by juancentro** [matbarofex/rRofex#13]
Hoy en dia los datos se devuelven en una forma muy normalizada. Desnormalizarla a una forma mas usable toma tiempo (que es valioso) y no muy friendly para gente sin muchos conocimientos de programacion. El principal uso de la mayoria de la gente sera traer los datos de la rueda en la estructura usual (Instrumento, Bid Size, Bid Px, Ask Px, Ask Size, Open Interest, etc)

**Comment by augustohassel** [comment]
Hola! subí una nueva versión que contempla la organización de la market data. 
https://github.com/matbarofex/rRofex/releases/tag/1.4.0
Fijate que las funciones ganan el parámetros "tidy" que puede ser TRUE o FALSE y te organiza el data frame.
Avisame que tal así cierro el issue.
