### ISSUE TITLE
Agregar columnas que permitan filtrar instrumentos a la security list

### ISSUE THREAD

**Issue by juancentro** [matbarofex/rRofex#14]
La tabla de instrumentos no especifica subyacente y tipo de producto (futuro, opcion). Deberian estar como minimo estas dos columnas.

**Comment by augustohassel** [comment]
Hola! Finalmente volví a retomar el desarrollo de esta librería. Fijate que agregué varias columnas con metadata y parámetros nuevos al método de `trading_instruments()`
Están en este release: v 0.0.1.0003 
`trading_instruments(connection = conn, request = "securities", sec_detailed = T)`
Probalos y contame, así cierro el issue.
Saludos!
PD: Estoy mejorando la documentación también: https://matbarofex.github.io/rRofex/reference/trading_instruments.html
