### ISSUE TITLE
Mejoras en método de pedido de Market Data via WebSocket

### ISSUE THREAD

**Issue by soberto** [matbarofex/rRofex#16]
Buenísimo el laburo que se le está metiendo!!

Le agregaría como new feature la posibilidad de:

1) Elegir entre ir agregando filas nuevas a la tabla donde se almacenan o bien guardar sólo el último, dependiendo de lo que se indique cuando se llame la función que trae la data de WS.

2) la posibildiad de guardar más de un activo en la tibble donde se guardan los update de WS.

3) Posibilidad que de verificar que ante la desconexión y nueva conexión no se agregue fila duplicada (se peude hace a mano pero si la función que trae la data y la agrega a la tibble lo puede verificar haciendo un distintc con los campos que corresponda sería más genial todavía!)

Me sumo a lo que se necesite para ir testeando y aportar en lo que se pueda!

Saludos!

**Comment by augustohassel** [comment]
La versión 2.0.0.9003 en el branch de websocket resuelve las dos últimas. La primera me falta aún.

**Comment by augustohassel** [comment]
Lo doy por cerrado, en caso de ser necesario lo vuelvo a abrir!
