### ISSUE TITLE
Falta ayuda en la consola

### ISSUE THREAD

**Issue by jfgomezok** [matbarofex/rRofex#2]
La librería no tiene ayuda cuando uno escribe `?rRofex`.

> No documentation for ‘rRofex’ in specified packages and libraries:
you could try ‘??rRofex’

**Comment by augustohassel** [comment]
Hola @jfgomezok ! Fijate de instalar nuevamente el paquete con:
`devtools::install_github("gruporofex/rRofex")`
Ya agregué un cambio que debería solucionar esto.
Gracias!

**Comment by jfgomezok** [comment]
Gracias! Instalé nuevamente el paquete, y el comando `?rRofex` ahora me devuelve esto:

> Error in fetch(key) : lazy-load database 'C:/Users/jgomez/Documents/R/win-library/3.5/rRofex/help/rRofex.rdb' is corrupt

**Comment by augustohassel** [comment]
Fijate que reiniciado R te va a cargar bien! 
Esto es lo que encontré: <https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database>
