### ISSUE TITLE
No está trayendo el Settlement Price

### ISSUE THREAD

**Issue by tzucca** [matbarofex/rRofex#21]
Cuando consulto por el MarketDataType SE no está viniendo información y si consulto por API viene la info:

/rest/marketdata/get?marketId=ROFX&symbol=SOJ.ROSNov20&entries=SE,CL

{
"status": "OK",
"marketData": {
"CL": {
"price": 243.5,
"size": null,
"date": 1596067200000
},
"SE": {
"price": 243.8,
"size": null,
"date": 1595980800000
}
},
"depth": 1,
"aggregated": true
}

**Comment by augustohassel** [comment]
@tzucca sigue ocurriendo esto? de ser así, me podrías pasar otro ejemplo nuevo así lo miro. Gracias!
