### ISSUE TITLE
New Feature: trading_ws_md ante actualización, mantenga sólo última observación en el dataframe destino

### ISSUE THREAD

**Issue by soberto** [matbarofex/rRofex#23]
### ESCENARIO

Usuario interesado en consumir market data real time para hacer cálculos. Uitliza principalmente las puntas y el last.

Con una conexión por WebSocket por symbol trae la información atualizada. Le interesa saber siempre el último valor y no todo el historial de actualizaciones.

### RESULTADO HOY

A medida que pasa el tiempo, con cada actualización de punta los dataframe donde se almacenan los registros de cambios observados por el WS crecen sustancialmente, cuando lo único que interesa utilizar es la última fila.

### SUGERENCIA

Que el método trading_ws_md, tenga una propiedad que permita setear si se quiere "pisar" la información existente a medida que se observan cambios, de manera que siempre, cada df donde los WS guardan la información tengan una dimensión igual a 1 (suponiendo que no se consume profundidad adicional).

**Comment by augustohassel** [comment]
@soberto muy buena idea. Veo si en las semanas que viene lo puedo implementar. Si tenes algo armado y queres ayudarme empezando un feature branch para este issue, es bienvenida la ayuda!
