### ISSUE TITLE
trading_md necesita la funcion "mutate"

### ISSUE THREAD

**Issue by jfgomezok** [matbarofex/rRofex#3]
La instrucción `trading_md(environment = "reMarkets", market_id = "ROFX", symbol = "DoJun19")` te devuelve el siguiente error:

> Error in mutate(., type = case_when(is.na(type) ~ "value", TRUE ~ type)) : 
  could not find function "mutate"
In addition: Warning message:
Expected 2 pieces. Missing pieces filled with `NA` in 1 rows [3].

**Comment by augustohassel** [comment]
Hola Fran!
Tenía mal configuradas las dependencias. 
Fijate de reinstalar el paquete!
