### ISSUE TITLE
En trading_instruments, en el mutate final, las regex no logran formatear la data correctamente.

### ISSUE THREAD

**Issue by Igna43** [matbarofex/rRofex#30]
Al utilizar la funcion `trading_instruments` las columnas `StrikePrice` trae NA porque la regex no logra capturar la data de la columna de origen.  Adicionalmente la columna `Underlying` queda con el mismo formato que la de `Symbol`

<img width="712" alt="trading_instruments" src="https://user-images.githubusercontent.com/64452330/136388838-0dad5d01-b1dd-4a05-9c6a-fdffb6dccdab.PNG">

**Comment by augustohassel** [comment]
@Igna43 esta resuelto en dev, te recomiendo usar esa rama hasta que se pase a CRAN. ffd47bf2f56040197554476cf54ca7d19b3c05df
