### ISSUE TITLE
Error al instalar

### ISSUE THREAD

**Issue by juancentro** [matbarofex/rRofex#4]
Estoy instalando en R 3.6.0 corriendo en Arch y tengo este error al instalar, sospecho que hay algun problema con la doc

devtools::install_github("gruporofex/rRofex")
Downloading GitHub repo gruporofex/rRofex@master
✔  checking for file ‘/tmp/RtmpIfmd2j/remotes428362817373/gruporofex-rRofex-2d3db71/DESCRIPTION’ ...
─  preparing ‘rRofex’:
✔  checking DESCRIPTION meta-information ...
   Warning: /tmp/RtmpfLgdX4/Rbuild6f977ab684d3/rRofex/man/trading_mdh.Rd:20: unknown macro '\item'
   Warning: /tmp/RtmpfLgdX4/Rbuild6f977ab684d3/rRofex/man/trading_mdh.Rd:22: unknown macro '\item'
   Warning: /tmp/RtmpfLgdX4/Rbuild6f977ab684d3/rRofex/man/trading_mdh.Rd:24: unexpected section header '\value'
   Warning: /tmp/RtmpfLgdX4/Rbuild6f977ab684d3/rRofex/man/trading_mdh.Rd:27: unexpected section header '\description'
   Warning: /tmp/RtmpfLgdX4/Rbuild6f977ab684d3/rRofex/man/trading_mdh.Rd:30: unexpected section header '\examples'
   Warning: /tmp/RtmpfLgdX4/Rbuild6f977ab684d3/rRofex/man/trading_mdh.Rd:33: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘rRofex_0.0.0.9001.tar.gz’
   
Installing package into ‘/home/juan/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘rRofex’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /tmp/Rtmp2sssBk/R.INSTALL6fa433317ba3/rRofex/man/trading_mdh.Rd:20: unknown macro '\item'
ERROR: installing Rd objects failed for package ‘rRofex’
* removing ‘/home/juan/R/x86_64-pc-linux-gnu-library/3.6/rRofex’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpIfmd2j/file42837b7b4b8f/rRofex_0.0.0.9001.tar.gz’ had non-zero exit status

**Comment by augustohassel** [comment]
Hola! Esta noche me conecto en un entorno similar y pruebo. Gracias por avisar!

**Comment by augustohassel** [comment]
Hola Juan! ya subí una nueva versión 0.0.0.9004 que arregla esto. 
Básicamente cuando documenté no tuve en cuenta que los % son caracteres especiales y tengo que escaparlos con '/'. 
Ya probé en Ubuntu. 
Fijate si podes desintalar el paquete, reiniciar R y volver a instalarlo. 
Saludos!

**Comment by juancentro** [comment]
Se instalo perfecto
